"""phase 3

Revision ID: 6dd8883efab0
Revises: 72ee7b020e99
Create Date: 2026-09-01 02:46:37.222025
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6dd8883efab0'
down_revision: Union[str, None] = '72ee7b020e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('entitlement_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', 'ONE_TIME', name='entitlementperiod'), nullable=False),
    sa.Column('max_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monetary_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['beneficiary_categories.id'], ),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['welfare_programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'category_id', 'commodity_id', name='uq_entitlement_rule_scope')
    )
    op.create_index(op.f('ix_entitlement_rules_category_id'), 'entitlement_rules', ['category_id'], unique=False)
    op.create_index(op.f('ix_entitlement_rules_commodity_id'), 'entitlement_rules', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_entitlement_rules_program_id'), 'entitlement_rules', ['program_id'], unique=False)
    op.create_table('welfare_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('mart_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('used_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('warning_threshold_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['beneficiary_categories.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['mart_id'], ['marts.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['welfare_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_welfare_budgets_program_id'), 'welfare_budgets', ['program_id'], unique=False)
    op.create_table('beneficiary_entitlement_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('entitlement_rule_id', sa.Integer(), nullable=False),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('allocated_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('used_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['entitlement_rule_id'], ['entitlement_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beneficiary_id', 'entitlement_rule_id', 'period_key', name='uq_beneficiary_rule_period')
    )
    op.create_index(op.f('ix_beneficiary_entitlement_usage_beneficiary_id'), 'beneficiary_entitlement_usage', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_beneficiary_entitlement_usage_entitlement_rule_id'), 'beneficiary_entitlement_usage', ['entitlement_rule_id'], unique=False)
    op.create_table('welfare_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_code', sa.String(length=30), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('mart_id', sa.Integer(), nullable=True),
    sa.Column('cashier_user_id', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'VOIDED', name='welfaretransactionstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['welfare_cards.id'], ),
    sa.ForeignKeyConstraint(['cashier_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mart_id'], ['marts.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['welfare_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_welfare_transactions_beneficiary_id'), 'welfare_transactions', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_welfare_transactions_card_id'), 'welfare_transactions', ['card_id'], unique=False)
    op.create_index(op.f('ix_welfare_transactions_mart_id'), 'welfare_transactions', ['mart_id'], unique=False)
    op.create_index(op.f('ix_welfare_transactions_transaction_code'), 'welfare_transactions', ['transaction_code'], unique=True)
    op.create_table('welfare_transaction_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('entitlement_rule_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['entitlement_rule_id'], ['entitlement_rules.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['welfare_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_welfare_transaction_items_transaction_id'), 'welfare_transaction_items', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_welfare_transaction_items_transaction_id'), table_name='welfare_transaction_items')
    op.drop_table('welfare_transaction_items')
    op.drop_index(op.f('ix_welfare_transactions_transaction_code'), table_name='welfare_transactions')
    op.drop_index(op.f('ix_welfare_transactions_mart_id'), table_name='welfare_transactions')
    op.drop_index(op.f('ix_welfare_transactions_card_id'), table_name='welfare_transactions')
    op.drop_index(op.f('ix_welfare_transactions_beneficiary_id'), table_name='welfare_transactions')
    op.drop_table('welfare_transactions')
    op.drop_index(op.f('ix_beneficiary_entitlement_usage_entitlement_rule_id'), table_name='beneficiary_entitlement_usage')
    op.drop_index(op.f('ix_beneficiary_entitlement_usage_beneficiary_id'), table_name='beneficiary_entitlement_usage')
    op.drop_table('beneficiary_entitlement_usage')
    op.drop_index(op.f('ix_welfare_budgets_program_id'), table_name='welfare_budgets')
    op.drop_table('welfare_budgets')
    op.drop_index(op.f('ix_entitlement_rules_program_id'), table_name='entitlement_rules')
    op.drop_index(op.f('ix_entitlement_rules_commodity_id'), table_name='entitlement_rules')
    op.drop_index(op.f('ix_entitlement_rules_category_id'), table_name='entitlement_rules')
    op.drop_table('entitlement_rules')
    op.drop_table('commodities')
    # ### end Alembic commands ###
