"""phase 2

Revision ID: 7189c8e7ff24
Revises: d139b2b8aae4
Create Date: 2026-08-30 18:18:13.002303
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7189c8e7ff24'
down_revision: Union[str, None] = 'd139b2b8aae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
