"""add beneficiary tables

Revision ID: 72ee7b020e99
Revises: 7189c8e7ff24
Create Date: 2026-08-30 19:05:28.985495
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '72ee7b020e99'
down_revision: Union[str, None] = '7189c8e7ff24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiary_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('welfare_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_code', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('father_husband_name', sa.String(length=150), nullable=True),
    sa.Column('cnic', sa.String(length=20), nullable=True),
    sa.Column('mobile_number', sa.String(length=30), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('tehsil', sa.String(length=100), nullable=True),
    sa.Column('union_council', sa.String(length=100), nullable=True),
    sa.Column('village_area', sa.String(length=150), nullable=True),
    sa.Column('family_size', sa.Integer(), nullable=True),
    sa.Column('number_of_children', sa.Integer(), nullable=True),
    sa.Column('employment_status', sa.String(length=50), nullable=True),
    sa.Column('household_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('income_source', sa.String(length=150), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('mart_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='beneficiarystatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['beneficiary_categories.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['mart_id'], ['marts.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['welfare_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiaries_beneficiary_code'), 'beneficiaries', ['beneficiary_code'], unique=True)
    op.create_index(op.f('ix_beneficiaries_category_id'), 'beneficiaries', ['category_id'], unique=False)
    op.create_index(op.f('ix_beneficiaries_cnic'), 'beneficiaries', ['cnic'], unique=False)
    op.create_index(op.f('ix_beneficiaries_district_id'), 'beneficiaries', ['district_id'], unique=False)
    op.create_index(op.f('ix_beneficiaries_mart_id'), 'beneficiaries', ['mart_id'], unique=False)
    op.create_index(op.f('ix_beneficiaries_program_id'), 'beneficiaries', ['program_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_code', sa.String(length=30), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('mart_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'VERIFICATION', 'APPROVED', 'CARD_ISSUED', 'REJECTED', 'REQUEST_MORE_INFO', 'SUSPENDED', 'EXPIRED', 'DEACTIVATED', name='applicationstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['beneficiary_categories.id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['mart_id'], ['marts.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['welfare_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_application_code'), 'applications', ['application_code'], unique=True)
    op.create_index(op.f('ix_applications_beneficiary_id'), 'applications', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_applications_category_id'), 'applications', ['category_id'], unique=False)
    op.create_index(op.f('ix_applications_district_id'), 'applications', ['district_id'], unique=False)
    op.create_index(op.f('ix_applications_mart_id'), 'applications', ['mart_id'], unique=False)
    op.create_index(op.f('ix_applications_program_id'), 'applications', ['program_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('welfare_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=30), nullable=False),
    sa.Column('qr_token', sa.String(length=64), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'BLOCKED', 'SUSPENDED', 'EXPIRED', 'LOST', 'REPLACED', 'DEACTIVATED', name='cardstatus'), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('mart_id', sa.Integer(), nullable=True),
    sa.Column('replaced_from_card_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['mart_id'], ['marts.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['welfare_programs.id'], ),
    sa.ForeignKeyConstraint(['replaced_from_card_id'], ['welfare_cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_index(op.f('ix_welfare_cards_beneficiary_id'), 'welfare_cards', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_welfare_cards_card_number'), 'welfare_cards', ['card_number'], unique=True)
    op.create_table('application_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='documentverificationstatus'), nullable=False),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('verification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_documents_application_id'), 'application_documents', ['application_id'], unique=False)
    op.create_table('verification_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_records_application_id'), 'verification_records', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_records_application_id'), table_name='verification_records')
    op.drop_table('verification_records')
    op.drop_index(op.f('ix_application_documents_application_id'), table_name='application_documents')
    op.drop_table('application_documents')
    op.drop_index(op.f('ix_welfare_cards_card_number'), table_name='welfare_cards')
    op.drop_index(op.f('ix_welfare_cards_beneficiary_id'), table_name='welfare_cards')
    op.drop_table('welfare_cards')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_program_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_mart_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_district_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_category_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_beneficiary_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_application_code'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_beneficiaries_program_id'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_mart_id'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_district_id'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_cnic'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_category_id'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_beneficiary_code'), table_name='beneficiaries')
    op.drop_table('beneficiaries')
    op.drop_table('welfare_programs')
    op.drop_table('beneficiary_categories')
    # ### end Alembic commands ###
