"""phase 2: beneficiaries

Revision ID: d139b2b8aae4
Revises: ea5152a60686
Create Date: 2026-08-30 16:28:12.871049
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd139b2b8aae4'
down_revision: Union[str, None] = 'ea5152a60686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
